### ISSUE TITLE
Backup failed

### ISSUE THREAD

**Issue by richardlm** [everruler12/roam2github-demo#1]
Hi
I have set up my R2G backup but got this error on first run:

`2021-02-01 16:25:46.467 R2G Creating browser
2021-02-01 16:25:46.703 R2G Navigating to login page
2021-02-01 16:25:47.957 R2G Signing in
2021-02-01 16:25:49.113 R2G Login successful!
2021-02-01 16:25:49.113 R2G Navigating to graph
2021-02-01 16:25:50.238 R2G astrolabe spinning...
2021-02-01 16:26:31.628 R2G astrolabe spinning stopped
2021-02-01 16:26:31.657 R2G Graph loaded!
2021-02-01 16:26:31.701 R2G ERROR - Error: Evaluation failed: TypeError: Cannot read property 'click' of undefined
    at __puppeteer_evaluation_script__:2:104
    at ExecutionContext._evaluateInternal (/home/runner/work/my-roam-backup/roam2github/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>) 
   at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/home/runner/work/my-roam-backup/roam2github/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
    at async /home/runner/work/my-roam-backup/roam2github/roam2github.js:161:13
R2G Exit after: 45.237s
Error: Process completed with exit code 1.
`
Any ideas of the cause?
Thx.

**Comment by everruler12** [comment]
That's a bit hard to read. I updated to add more verbose logging. Please Re-run jobs 
![image](https://user-images.githubusercontent.com/64292121/106492851-a52be280-6475-11eb-920c-75c090e83021.png)
If the error occurs again, you can attach a screenshot

**Comment by richardlm** [comment]
I attach the backup log - I hope that provides more useful information.
Thanks.
[1_Backup.txt](https://github.com/everruler12/roam2github-demo/files/5905574/1_Backup.txt)

**Comment by everruler12** [comment]
Yes, the attached backup log is perfect. It's failing when trying to open the `...` menu or clicking the `Export All` option. I added an extra check to see which of these two is failing. Please run again.

Also, can you tell me what version your Roam is?
(Can be found by clicking the `?` button in lower-right corner and scrolling down to the very bottom of the popup)
Then `Check for updates` from the `...` button in upper-right

Sometimes Roam says it's up to date (current version I'm on says `0.8.1-80d9e52c`), but it's actually not, and won't update until you clear your cache. So when the backup script runs, it may be getting an orange popup notification saying there's an update, blocking the Export option from being clicked.

**Comment by HybridRbt** [comment]
I have the exact same problem "Cannot read property 'click' of undefined...". But if I re-run the job manually it would finish without problem. Happened twice since I set it up this morning. Seems like the initial run after setup was fine, and then all fine for 2 times, but for the 3rd time (which is the latest one) it failed. 

My Roam is at 0.8.1-80d9e52c.

**Comment by everruler12** [comment]
I've pushed an update that adds stricter checks to make sure the elements being clicked actually exist, instead of assuming they exist just because their parent element does. Closing this issue. Please re-open if you keep getting `Cannot read property 'click' of undefined` errors.
